App.Debtor.FIXTURES = [
  {
    "id": 4103752,
    "type": "N",
    "title": null,
    "firstName": "Joseph",
    "middleName": "",
    "lastName": "Best",
    "suffix": null,
    "dob": null,
    "ssn": null,
    "maritalStatus": 0,
    "email": null,
    "emailValidity": null,
    "optIn": null,
    "commContact": null,
    "country": 231,
    "address1": "4420 Green Wood",
    "address2": null,
    "address3": null,
    "city": "Shreveport",
    "state": "LA",
    "zip": "71109",
    "county": null,
    "dlIssuer": null,
    "dlNumber": null,
    "passport": null,
    "pin": "0263"
  },
  {
    "id": 4103753,
    "type": "N",
    "title": null,
    "firstName": "Jennifer",
    "middleName": null,
    "lastName": "Scneeweis",
    "suffix": null,
    "dob": null,
    "ssn": null,
    "maritalStatus": 0,
    "email": null,
    "emailValidity": null,
    "optIn": null,
    "commContact": null,
    "country": 231,
    "address1": "1815 N 45Th St Ste 218",
    "address2": null,
    "address3": null,
    "city": "Seattle",
    "state": "WA",
    "zip": "98103",
    "county": null,
    "dlIssuer": null,
    "dlNumber": null,
    "passport": null,
    "pin": "6685"
  }
]