App.Employment = DS.Model.extend
  relationship:       DS.attr 'string'
  name:               DS.attr 'string'
  monthlyNetIncome:   DS.attr 'number'
  position:           DS.attr 'string'
  hireDate:           DS.attr 'date'
  phone:              DS.attr 'string'
  website:            DS.attr 'string'
  status:             DS.attr 'string'
  source:             DS.attr 'string'
  jobTitle:           DS.attr 'string'
  terminationDate:    DS.attr 'date'
  yearlyIncome:       DS.attr 'number'
  monthlyGrossIncome: DS.attr 'number'

  country:            DS.attr 'string'
  address1:           DS.attr 'string'
  address2:           DS.attr 'string'
  address3:           DS.attr 'string'
  city:               DS.attr 'string'
  state:              DS.attr 'string'
  zip:                DS.attr 'string'
  county:             DS.attr 'string'

  debtor:             DS.belongsTo 'App.Debtor'